/****** Object:  Procedure [dbo].[s_CreateWorkOrder]    Committed by VersionSQL https://www.versionsql.com ******/

CREATE   PROCEDURE [dbo].[s_CreateWorkOrder] @strPushDate as varchar(20), @machine as varchar(50)
AS
declare @machineid as nvarchar(50)
declare @componentid as nvarchar(50)
declare @operationno as smallint
declare @WOno as nvarchar(50)
declare @CycleTime as float
declare @price as float
declare @customerid as varchar(50)
declare @sttime as datetime
declare @ndtime as datetime
declare @eid as varchar(25)
declare @mc as varchar(4)
declare @comp as varchar(4)
declare @opn as varchar(4)
declare @opr as varchar(50)
declare @count as int
declare @PushDate as datetime
select @PushDate = convert(datetime, @strpushdate, 103)
declare @pushdatebegin as datetime
declare @pushdateend as datetime
select @pushdatebegin = convert(datetime, @strpushdate + ' 00:00:00', 103 )
select @pushdateend = convert(datetime, @strpushdate + ' 23:59:59', 103 )
DECLARE CurWO CURSOR FOR
SELECT DISTINCT mc,comp,opn,machineid, componentid,
operationno, customerid
FROM v_WOData
where machineid = @machine and
((sttime <= @pushdatebegin And ndtime >= @pushdateend)
or (sttime > @pushdatebegin And sttime < @pushdateend And ndtime >= @pushdateend)
or (sttime > @pushdatebegin And sttime < @pushdateend And ndtime > @pushdatebegin And ndtime < @pushdateend)
or (sttime <= @pushdatebegin And ndtime < @pushdateend And ndtime > @pushdatebegin)
	)
and post = 0
order by machineid, customerid, componentid, operationno
OPEN CurWO
FETCH NEXT FROM CurWO Into @mc,@comp, @opn, @machineid, @componentid, @operationno, @customerid
WHILE @@FETCH_STATUS = 0
BEGIN
--check to see if a workorder exists for a given mc, opr, opn, com and wodate
select @count=count(*) from workorderheader where
	machineid = @machineid and componentid= @componentid
	and operationno= @operationno
	and wodate= @pushdate
	and customerid = @customerid
	
PRINT @COUNT
If @count = 0
	begin
--check to see how many workorders are present for that machine and that date
select @count=count(*) from workorderheader where wodate=@pushdate and machineid=@machineid
		
	
--generate workorder by concatenating machineid, push date and a number.
--This number can be calculated by determining the number of work orders present for that machine and date
--that are already present in the WorkOrderHeader table.
--If no work orders exist for that machine and date, the number is 1
If @count = 0
select @wono = @machineid + '-' + convert(varchar(15),@pushdate,106)+ '-1'
Else
select @wono = @machineid + '-' + convert(varchar(15),@pushdate,106)+ '-' + cast(@count+1 as varchar(2))
	
	    select @price=price ,@cycletime=cycletime from componentoperationpricing where componentid=@componentid and operationno=@operationno
insert into workorderheader (workorderno,machineid,customerid,componentid,operationno,price,cycletime,wodate,autogenerated) values
		(@wono,@machineid,@customerid,@componentid,@operationno,@price,@cycletime,@pushdate,1)
	end
FETCH NEXT FROM CurWO into @mc,@comp, @opn, @machineid, @componentid, @operationno, @customerid
END
CLOSE CurWO
DEALLOCATE CurWO
