/****** Object:  Procedure [dbo].[s_GetRejectionCodeListreport]    Committed by VersionSQL https://www.versionsql.com ******/

--Procedure generated by Shilpa H.M on 16 nov 07 for report SM_rejectioncodelisting.rpt
--mod 1 :- ER0182 By Kusuma M.H on 19-May-2009. Modify all the procedures to support unicode characters. Qualify with leading N.
--Note:Component and operation not qualified.So,ER0181 not done.


CREATE   PROCEDURE [dbo].[s_GetRejectionCodeListreport]
@category nvarchar(50) = ''

as

begin

Declare @strsql as nvarchar(1000)

select @strsql = 'select rejectioncodeinformation.rejectionid,rejectioncodeinformation.rejectiondescription,'
select @strsql=    @strsql + 'rejectioncodeinformation.catagory from rejectioncodeinformation'
 
if isnull(@category, '') <> '' 
	begin
	--print 'in if'
	---mod 1
--	select @strsql = @strsql + ' WHERE ' + '(Catagory ='''+ @category +''')'
	select @strsql = @strsql + ' WHERE ' + '(Catagory =N'''+ @category +''')'
	---mod 1
	end

select @strsql= @strsql + ' order by rejectioncodeinformation.rejectionid asc'
exec(@strsql)
print @strsql
end
